<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clouder.Core\Clouder.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.4162" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.5" />
  </ItemGroup>

</Project>
